# Generated by Django 4.2.2 on 2023-06-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_imageclassfication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
