# Generated by Django 4.2.2 on 2023-06-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_imagemodel_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
